eureka:
  client:
    enabled: false
springdoc:
  api-docs:
    enabled: true
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: game-db
      port: 27017
      host: localhost
